#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 21 15:54:33 2020

@author: nick
"""

'''
Implementation of a Gaussian mixture model which is fit using a cross-entropy
minimizing EM-type procedure.
'''

import sklearn.mixture as mx